version: '3.9'
services:
  cel-web:
    container_name: cel-web
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_URL
      - CONGRESS_GOV_API_KEY_1
      - CONGRESS_GOV_API_KEY_2
      - CONGRESS_GOV_API_BASE_URL
    volumes:
      - .:/app
    command: yarn dev
    ports:
      - 3000:3000
      - 49153:49153
    depends_on:
      - cel-cache
  cel-ws:
    container_name: cel-ws
    build:
      context: .
      dockerfile: ws.Dockerfile
    volumes:
      - .:/app
    command: yarn nodemon --watch src --ext .ts,.tsx,js,jsx --signal SIGTERM --exec "yarn tsx --tsconfig /app/tsconfig.ws.json /app/src/server/ws/index.ts"
    ports:
      - 3030:3030
    expose:
      - 3030
    depends_on:
      - cel-cache
  cel-workers:
    container_name: cel-workers
    build:
      context: .
      dockerfile: w.Dockerfile
    environment:
      - DB_URL
      - CONGRESS_GOV_API_KEY_1
      - CONGRESS_GOV_API_KEY_2
      - CONGRESS_GOV_API_BASE_URL
    volumes:
      - .:/app
      - ${SSH_PATH}:/.ssh
    command: yarn nodemon --watch src/workers --watch src/assets --ext .ts --signal SIGTERM --exec "tsc --project /app/src/workers/tsconfig.json && node /app/.workers/src/workers/index.js"
    depends_on:
      - cel-cache
  cel-cache:
    container_name: cel-cache
    image: redis:7.0.4-alpine
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - cel-redis-data:/data

volumes:
  cel-redis-data:
